### ISSUE TITLE
Some errors is not showing when error is replicated

### ISSUE THREAD

**Issue by luqmanrom** [bahmutov/console-log-div#11]
![screen shot 2015-02-03 at 4 08 19 pm](https://cloud.githubusercontent.com/assets/6434819/6030710/f9b46d66-abbe-11e4-96f8-2891d68e3c92.png)

Some errors is not showing when it is replicated.

**Comment by bahmutov** [comment]
when you do `throw new Error();` or `a.apply` you do not call `console.error` - it happens behind the scenes inside Chrome, so it is not possible to mirror these exceptions. Instead you can catch errors using window.onerror handler. This is much deeper topic and I would suggest using real time crash reporting service, like Sentry. Read my blog posts on catching errors http://bahmutov.calepin.co/tag/sentry.html

**Comment by bahmutov** [comment]
I added error event listener - should be enough to print any unhandled thrown Errors, check out v0.4.0

**Comment by luqmanrom** [comment]
Great! Good job!
